[DVWA]
# 靶機的根目錄 URL (請確認結尾不要有斜線)
#base_url = http://192.168.1.100/dvwa
base_url_Linux = http://10.0.0.16/dvwa
base_url_alone_Win = http://192.168.55.2/dvwa
base_url_AD_Win = http://192.168.55.3/dvwa
# 預設登入帳密
username = admin
password = password
# 預設測試的安全等級 (low, medium, high)
default_security_level = low
